# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fe1765cdcbba629f617414417f22b476986bd4dacaff4d825b9f8bc12ac3c0b4b976aa01c4f49b8bf1f9840d957e61dc9f863bdda2883da9b2f7ce53865b5c7

test:
  secret_key_base: 71e38a8b4eac192fd78709fc254e20a3536067e568a6663f90ebfb323d87ad769028b0b2cde86fefe316de6e8f374b71fb9ad65bbb0620389809b07cdafac4e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
